"""message

Revision ID: b898eca021ec
Revises: c91ac61a39a2
Create Date: 2024-07-21 22:14:57.684077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b898eca021ec'
down_revision = 'c91ac61a39a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
